# Generated by Django 2.2.6 on 2019-11-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Test_end_session',
            fields=[
                ('id_test', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('q1', models.TextField()),
                ('a1', models.TextField()),
                ('q2', models.TextField()),
                ('a2', models.TextField()),
                ('q3', models.TextField()),
                ('a3', models.TextField()),
                ('q4', models.TextField()),
                ('a4', models.TextField()),
                ('q5', models.TextField()),
                ('a5', models.TextField()),
                ('q6', models.TextField()),
                ('a6', models.TextField()),
                ('q7', models.TextField()),
                ('a7', models.TextField()),
                ('q8', models.TextField()),
                ('a8', models.TextField()),
                ('q9', models.TextField()),
                ('a9', models.TextField()),
                ('q10', models.TextField()),
                ('a10', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_mcq_end_session',
            fields=[
                ('id_test', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('id_q', models.IntegerField()),
                ('question', models.CharField(max_length=50)),
                ('Choice_num', models.IntegerField()),
                ('Choice_num_exp', models.IntegerField()),
                ('Choice_text_correspnd', models.TextField()),
            ],
            options={
                'unique_together': {('id_test', 'id_q')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test')),
            ],
        ),
        migrations.CreateModel(
            name='PassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.CharField(max_length=10)),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('check_button', models.BooleanField(blank=True, default=False)),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Pass_test_mcq_end_session',
            fields=[
                ('id_pass_test', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_student', models.CharField(max_length=10)),
                ('id_q', models.IntegerField()),
                ('input_Choice_num', models.IntegerField()),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test_mcq_end_session')),
            ],
            options={
                'unique_together': {('id_pass_test', 'id_student', 'id_q')},
            },
        ),
        migrations.CreateModel(
            name='Pass_test_end_session',
            fields=[
                ('id_pass_test', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_student', models.CharField(max_length=10)),
                ('q1', models.TextField()),
                ('q2', models.TextField()),
                ('q3', models.TextField()),
                ('q4', models.TextField()),
                ('q5', models.TextField()),
                ('q6', models.TextField()),
                ('q7', models.TextField()),
                ('q8', models.TextField()),
                ('q9', models.TextField()),
                ('q10', models.TextField()),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test_end_session')),
            ],
            options={
                'unique_together': {('id_pass_test', 'id_student')},
            },
        ),
    ]
