# Generated by Django 2.2.6 on 2019-11-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='choice',
            name='check_button',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
