# Generated by Django 2.2.6 on 2019-11-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_choice_is_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyze_test_end_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_analyze', models.CharField(max_length=10)),
                ('list_answer_q1', models.TextField()),
                ('list_answer_q2', models.TextField()),
                ('list_answer_q3', models.TextField()),
                ('list_answer_q4', models.TextField()),
                ('list_answer_q5', models.TextField()),
                ('list_answer_q6', models.TextField()),
                ('list_answer_q7', models.TextField()),
                ('list_answer_q8', models.TextField()),
                ('list_answer_q9', models.TextField()),
                ('list_answer_q10', models.TextField()),
            ],
        ),
    ]
